// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */


 
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
        type: 'category',
        label: 'Getting Started',
        link: {type: 'doc', id: 'start/intro'},
        items: [
                'start/demo',
                'start/commercial',
                'start/makers',
                'start/education',
        ],
    },
    {
        type: 'category',
        label: 'Module Catalog',
        link: {type: 'doc', id: 'catalog/intro'},
        items: [
                {
                    type: 'category',
                    label: 'Mainboards',
                    link: {
                      type: 'doc',
                      id: 'catalog/mainboards',
                    },
                    items: [{
                        type: 'autogenerated',
                        dirName: 'catalog/mainboard',
                    }]
                },
                
                {
                    type: 'category',
                    label: 'Displays',
                    link: {
                      type: 'doc',
                      id: 'catalog/displays',
                    },
                    items: [{
                        type: 'autogenerated',
                        dirName: 'catalog/display',
                    }]
                },
                {
                    type: 'category',
                    label: 'Actuators',
                    link: {
                      type: 'doc',
                      id: 'catalog/actuators',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/actuator',
                       },             
                    ]
                },
                {
                    type: 'category',
                    label: 'Communication',
                    link: {
                      type: 'doc',
                      id: 'catalog/com',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/com',
                       },             
                    ]
                },
                {
                    type: 'category',
                    label: 'Human Machine Interface',
                    link: {
                      type: 'doc',
                      id: 'catalog/hmi',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/hmi',
                       },             
                    ]
                },
                { 
                    type: 'category',
                    label: 'Storage',
                    link: {
                      type: 'doc',
                      id: 'catalog/storage',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/storage',
                       },             
                    ]
                },
                {
                    type: 'category',
                    label: 'Wireless',
                    link: {
                      type: 'doc',
                      id: 'catalog/wireless',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/wireless',
                       },             
                    ]
                },
                {
                    type: 'category',
                    label: 'Sensors',
                    link: {
                      type: 'doc',
                      id: 'catalog/sensors',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/sensor',
                       },             
                    ]
                },
                {
                    type: 'category',
                    label: 'LEDs',
                    link: {
                      type: 'doc',
                      id: 'catalog/leds',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/led',
                       },             
                    ]
                },
                {
                    type: 'category',
                    label: 'Sound',
                    link: {
                      type: 'doc',
                      id: 'catalog/sound',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/sound',
                       },             
                    ]
                },
                {
                    type: 'category',
                    label: 'Accessories',
                    link: {
                      type: 'doc',
                      id: 'catalog/accessories',
                    },
                    items: [
                       {
                        type: 'autogenerated',
                        dirName: 'catalog/accessory',
                       },             
                    ]
                },
                'catalog/third-party',
        ],
    },

    {
        type: 'category',
        label: 'Supported Systems',
        link: {type: 'doc', id: 'system/intro'},
        items: [
                'system/raspberry-pi',
                'system/beagleboard',
                'system/microbit',  
                'system/arduino',
                'system/pc-laptop',
                'system/phone-tablet',
                'system/beyond',
                
        ],
    },

    {
        type: 'category',
        label: 'Hosted Languages',
        link: {type: 'doc', id: 'language/intro'},
        items: [
          {
            type: 'category',
            label: 'Core API',
            //link: {type: 'doc', id: 'api/intro'},
            items: [{
              type: 'autogenerated',
              dirName: 'api',
          }],
          },
                'language/python',
                'language/micropython',
                'language/javascript',
                'language/typescript',
                'language/dotnet',
                'language/tinyclr',
                'language/cpp',    
                'language/swift',   
                'language/app-inventor',   
                'language/excel',
                'language/other',
                
        ],     
    },  
     
    {
        type: 'category',
        label: 'Interfaces',
        link: {type: 'doc', id: 'interface/intro'},
        items: [
                'interface/usb',
                'interface/i2c',
                'interface/uart',
                'interface/spi',
                'interface/downstream',
                'interface/wireless',              
        ],
    },
    {
        type: 'category',
        label: 'Internal Engine',
        link: {type: 'doc', id: 'engine/intro'},
        items: [
                'engine/scripting',
                'engine/standalone',
                'engine/daisylink',
                'engine/stdlib',
                'engine/streams',
                'engine/samples',          
        ],
    },
    'console',
    'loader',
    'specs',
    {
        type: 'category',
        label: 'Downloads',
        link: {type: 'doc', id: 'downloads'},
        items: [
                'release-notes',              
        ],
    },
    'support',
    'legal',
    'about',

    {
        type: 'link',
        label: 'GHI Electronics',
        href: 'https://www.ghielectronics.com/',
    },
    {
        type: 'link',
        label: 'Comunity Forum',
        href: 'https://forums.ghielectronics.com/c/duelink/31',
    },
   



  ],

};

export default sidebars;
