// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "What is DUELink?",
      link: { type: "doc", id: "what-is" },
      items: [
        "engineers",
        "makers",
        "educators",
      ],
    },
    "start",
    {
      type: "category",
      label: "Product Catalog",
      link: {type: 'doc', id: 'catalog/intro'},
      items: [
        {
          type: "category",
          label: "Kits",
          items: [
            "products/ktessen-a",
            "products/ktgimme-a"
          ],
        },
        {
          type: "category",
          label: "Microcomputers",
          items: [
            "products/mcdueduino-a",
            "products/mcstamp-b",
            "products/mcstick-a",
            "products/mccincobit-e",
            "products/mcclipit-b",
            "products/mcduestem-b",
            "products/mcpixobit-d"
          ],
        },
        {
          type: "category",
          label: "Specialty",
          items: [
            "products/spghizzyjr-a",
            "products/spghizzy-d",
            "products/sptree-b",
            "products/spsnowy-a",
            "products/spcubicle-a",
            "products/spchrono-a",
            "products/sppiano-a",
            "products/spctrlr-a"
          ],
        },
        {
          type: "category",
          label: "Adapters",
          items: [
            "products/adbreakout-a",
            "products/addueshield-a",
            "products/adduembus-a",
            "products/admbuslink-a",
            "products/adduepi-b",
            "products/adrpilink-a",
            "products/adduepico-b",
            "products/adlinkbit-a",
            "products/adravebit-a",
            "products/adpwrhook-a",
            "products/adpwrinj-a",
            "products/adpullup-a",
            "products/adpwrswch-a",
            "products/adsticker-c",
            "products/adusbhook-a",
            "products/adusbstick-a",
            "products/adusbwedge-b"
          ],
        },
        {
          type: "category",
          label: "Displays",
          items: [
            "products/dsepaprm29-a",
            "products/dsepaprm42-a",
            "products/dshdmi-b",
            "products/dslcd16x2-c",
            "products/dslcd20x4-b",
            "products/dsoled096-a",
            "products/dsprtlcp70-b",
            "products/dstftcp23-b",
            "products/dstftn18-b",
            "products/dstftr128-b",
            "products/dsvfdb8-c"
          ],
        },
        {
          type: "category",
          label: "Sensors",
          items: [
            "products/seaccel-a",
            "products/seairqlty-a",
            "products/sebaro-b",
            "products/seclipsen-a",
            "products/securrent-a",
            "products/sedistance-b",
            "products/sedof9-c",
            "products/seekg-a",
            "products/segas-b",
            "products/selight-a",
            "products/semotion-b",
            "products/seprsr-b",
            "products/sertc-b",
            "products/setemphmd-b",
            "products/setemprtd-a",
            "products/setempan-a"
          ],
        },
        {
          type: "category",
          label: "Actuators",
          items: [
            "products/acfan-b",
            "products/acload-a",
            "products/acdiox12-a",
            "products/acmotomax-b",
            "products/acmototwin-b",
            "products/acrelayp16-a",
            "products/acrelayp4-c",
            "products/acrelayx1-a",
            "products/acservop8-b",
            "products/acservox1-a",
            "products/acstepdp1-a",
            "products/acstepdp3-b",
            "products/acstepp-a"
          ],
        },
        {
          type: "category",
          label: "Communication",
          items: [
            "products/cmcan-b",
            "products/cmdmx-b",
            "products/cmethernet-c",
            "products/cmrs485-a",
            "products/cmserusb-a",
          ],
        },
        {
          type: "category",
          label: "Human Machine Interface",
          items: [
            "products/hibtnar100-b",
            "products/hibrgb284-b",
            "products/hibuttonl-a",
            "products/hibuttonl7-b",
            "products/hibuttons7-a",
            "products/hibuttons-a",
            "products/hidial-a",
            "products/hidipswch-b",
            "products/hifngrprnt-b",
            "products/hijoystkl-c",
            "products/hikeyp3x4-b",
            "products/hikeyp4x4-b",
            "products/hirotary-c",
            "products/hislider-b"
          ],
        },
        {
          type: "category",
          label: "Storage",
          items: [
            "products/stflash-a",
            "products/stmicrosd-a",
            "products/stsdcard-b",
              "products/stusbhost-b",
          ],
        },
        {
          type: "category",
          label: "Wireless",
          items: [
            "products/wlesp32-a",
            "products/wlgnsswa-a",
            "products/wlgnss-b",
            "products/wlinfrared-a",
            "products/wlnrf24max-c",
            "products/wlnrf24min-c",
            "products/wlrfid-b"
          ],
        },
        {
          type: "category",
          label: "LEDs",
          items: [
            "products/ldmt1208-a",
            "products/ldledr16-b",
            "products/ldledrgb3-a",
            "products/ldleds284-b",
            "products/ldleds404-a",
            "products/ldleds564-a",
            "products/ldledss805-c",
            "products/ldsmartled-b"
          ],
        },
        {
          type: "category",
          label: "Sound",
          items: [
            "products/sobuzzer-b",
            "products/sojack-a",
            "products/somp3-a",
            "products/soradiofm-a",
            "products/sospectrum-a"
          ],
        },
        {
          type: "category",
          label: "Vision",
          items: [
            "products/vibcodel12-a",
            "products/vithermal-a"
          ],
        },
        {
          type: "category",
          label: "Accessories",
          items: [
            "products/axcbl",
            "products/axcnctr",
            "products/axholey",
            "products/axmnt"
          ],
        },
        "catalog/third-party",
         {
          type: "category",
          label: "Our Lab!",
          link: { type: "doc", id: "catalog/lab" },
          items: [
            {
              type: "autogenerated",
              dirName: "catalog/lab",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Supported Hardware",
      link: { type: "doc", id: "hw/intro" },
      items: [
        "hw/raspberry-pi",
        "hw/arduino",
        "hw/espressif",
        "hw/microbit",
        "hw/arcade",
        "hw/beagleboard",
        "hw/pc-laptop",
        "hw/phone-tablet",
        "hw/beyond",
      ],
    },
    {
      type: "category",
      label: "Coding Languages",
      link: { type: "doc", id: "language/intro" },
      items: [
        "language/standalone",
        "language/python",
        "language/micropython",
        "language/javascript",
        "language/dotnet",
        "language/microblocks",
        "language/makecode",
        "language/app-inventor",
        "language/cpp",
        "language/swift",
        "language/excel",
        "language/other",
      ],
    },

    {
      type: "category",
      label: "Interfaces",
      link: { type: "doc", id: "interface/intro" },
      items: [
        "interface/usb",
        "interface/i2c",
        "interface/uart",
        "interface/downlink",
        "interface/wireless",
      ],
    },
    {
      type: "category",
      label: "Internal Engine",
      link: { type: "doc", id: "engine/intro" },
      items: [
        "engine/scripting",
        "engine/stdlib",
        "engine/drivers",
        "engine/graphics",
        "engine/filesystem",
        "engine/regions",
        "engine/scheduler",
        "engine/interrupt",
        "engine/daisylink",
        "engine/stream",
        "engine/coprocessor",
        /*{
          type: "category",
          label: "Samples",
          //link: {type: 'doc', id: 'api/intro'},
          items: [
            {
              type: "autogenerated",
              dirName: "engine/samples",
            },
          ],
        },*/
      ],
    },
    {
      type: "category",
      label: "IoT Cloud",
      link: { type: "doc", id: "iot/intro" },
      items: [
        "iot/aws",
        "iot/azure",
      ],
    },
    {
    type: "category",
    label: "Tools",
    items: [
        "console",
        "programmer",
        "loader",
      ],
  },
    "specs",
    {
      type: "category",
      label: "Downloads",
      link: { type: "doc", id: "downloads" },
      items: ["release-notes"],
    },
    "support",
    "legal",
    "safety",
    /*
    {
        type: 'link',
        label: 'GHI Electronics',
        href: 'https://www.ghielectronics.com/',
    },
    {
        type: 'link',
        label: 'Comunity Forum',
        href: 'https://forums.ghielectronics.com/c/duelink/31',
    },
   
*/
  ],
};

export default sidebars;
