// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Simplified sidebar structure (branch: simplified).
 *
 * Top-level sections (in order):
 *   🚀 Start Here          – everything a new user needs to send a command
 *   🎓 For Educators       – MicroBlocks workflow + curriculum
 *   ⚡ On-Module Code       – Arduino IDE / C++ (code that runs on the module)
 *   🛒 Catalog             – product browse by category
 *   🔌 Hosts               – per-platform setup (host-side)
 *   📚 Advanced            – internals: interfaces, engine, IoT, console, etc.
 *   📥 Resources           – projects, downloads, support, legal
 *
 * Placeholders:
 *   "Use from Your Code"  -> language/intro (will become a unified page)
 *   "Chain Modules"       -> engine/daisylink (will become a simpler page)
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    // ─────────────────────────────── 🚀 START HERE ───────────────────────────────
    {
      type: "category",
      label: "🚀 Start Here",
      collapsed: false,
      link: { type: "doc", id: "what-is" },
      items: [
        "what-is",
        { type: "doc", id: "start", label: "Get Started" },
        { type: "doc", id: "loader", label: "Update Firmware (if needed)" },
        { type: "doc", id: "chain", label: "Chain Modules" },
      ],
    },

    // ─────────────────────────────── 🎓 FOR SCHOOLS ──────────────────────────────
    {
      type: "category",
      label: "🎓 For Educators",
      link: { type: "doc", id: "educators" },
      items: [
        "language/microblocks",
        {
          type: "category",
          label: "CincoBit Curriculum",
          link: { type: "doc", id: "tutorial/cincobit" },
          items: [
            { type: "autogenerated", dirName: "tutorial/cincobit" },
          ],
        },
        {
          type: "category",
          label: "Tutorials",
          items: [
            "tutorial/ghizzy",
            "tutorial/duestem",
            "tutorial/essentials-kit",
          ],
        },
      ],
    },

    // ─────────────────────────────── ⚡ ON-MODULE CODE ───────────────────────────
    {
      type: "category",
      label: "⚡ On-Module Code",
      link: { type: "doc", id: "language/standalone" },
      items: ["language/arduino-ide", "language/cpp"],
    },

    // ─────────────────────────────── 🛒 CATALOG ──────────────────────────────────
    {
      type: "category",
      label: "🛒 Catalog",
      link: { type: "doc", id: "catalog/products" },
      items: [
        {
          type: "category",
          label: "Kits",
          items: [
            "products/ktessen-a",
            "products/ktgimme-a",
            "products/ktcincobit-e",
          ],
        },
        {
          type: "category",
          label: "Microcomputers",
          items: [
            "products/mccincobit-e",
            "products/mcclipit-b",
            "products/mcdueduino-a",
            "products/mcduestem-b",
            "products/mcpixobit-d",
            "products/mcstamp-b",
            "products/mcstick-a",
          ],
        },
        {
          type: "category",
          label: "Specialty",
          items: [
            "products/spchrono-a",
            "products/spctrlr-b",
            "products/spghizzy-d",
            "products/spghizzyjr-b",
            "products/sptree-b",
            "products/sppiano-b",
            "products/spsnowy-a",
          ],
        },
        {
          type: "category",
          label: "Displays",
          items: [
            "products/dsepaprm29-a",
            "products/dsepaprm42-a",
            "products/dshdmi-b",
            "products/dslcd16x2-c",
            "products/dslcd20x4-b",
            "products/dsoled096-a",
            "products/dsprtlcp70-b",
            "products/dstftcp23-b",
            "products/dstftn18-b",
            "products/dstftr128-b",
            "products/dsvfdb8-c",
          ],
        },
        {
          type: "category",
          label: "Sensors",
          items: [
            "products/seaccel-a",
            "products/seairqlty-a",
            "products/seclipsen-a",
            "products/securrent-a",
            "products/sedistance-b",
            "products/sedof9-c",
            "products/segas-b",
            "products/selight-a",
            "products/semotion-b",
            "products/seprsr-b",
            "products/sertc-b",
            "products/setemphmd-b",
            "products/setempan-a",
            "products/sethermo-a",
          ],
        },
        {
          type: "category",
          label: "Actuators",
          items: [
            "products/acdiox12-a",
            "products/acfan-b",
            "products/acload-a",
            "products/acmotomax-b",
            "products/acmototwin-b",
            "products/acrelayp16-a",
            "products/acrelayp4-c",
            "products/acrelayx1-a",
            "products/acservop8-b",
            "products/acservox1-a",
            "products/acstepdp1-a",
            "products/acstepdp3-b",
            "products/acstepp-a",
          ],
        },
        {
          type: "category",
          label: "Human Machine Interface",
          items: [
            "products/hibtnar100-b",
            "products/hibrgb284-b",
            "products/hibuttonl-a",
            "products/hibuttonl7-b",
            "products/hibuttons-a",
            "products/hibuttons7-a",
            "products/hidial-a",
            "products/hidipswch-b",
            "products/hifngrprnt-b",
            "products/hijoystkl-c",
            "products/hikeyp-b",
            "products/hirotary-c",
            "products/hislider-b",
          ],
        },
        {
          type: "category",
          label: "Storage",
          items: [
            "products/stflash-a",
            "products/stmicrosd-a",
            "products/stsdcard-b",
            "products/stusbhost-b",
          ],
        },
        {
          type: "category",
          label: "Wireless",
          items: [
            "products/wlgps-a",
            "products/wlnrf24min-c",
            "products/wlrfid-b",
            "products/wlesp32-a",
          ],
        },
        {
          type: "category",
          label: "LEDs",
          items: [
            "products/ldmt1208-a",
            "products/ldledr16-b",
            "products/ldledrgb3-a",
            "products/ldleds284-b",
            "products/ldleds404-a",
            "products/ldleds564-a",
            "products/ldledss805-c",
            "products/ldsmartled-b",
          ],
        },
        {
          type: "category",
          label: "Sound",
          items: [
            "products/sobuzzer-b",
            "products/somp3-a",
            "products/soradiofm-a",
            "products/soretrosnd-a",
            "products/sospectrum-a",
          ],
        },
        {
          type: "category",
          label: "Vision",
          items: ["products/vibcodel12-a", "products/vithermal-a"],
        },
        {
          type: "category",
          label: "Communication",
          items: [
            "products/cmcan-b",
            "products/cmdmx-b",
            "products/cmethernet-c",
            "products/cmrs485-a",
            "products/cmserusb-a",
          ],
        },
        {
          type: "category",
          label: "Adapters",
          items: [
            "products/adbreakout-a",
            "products/adduembus-a",
            "products/adduepi-b",
            "products/adduepico-b",
            "products/addueshield-a",
            "products/adlinkbit-a",
            "products/admbuslink-a",
            "products/adpwrhook-a",
            "products/adpwrinj-a",
            "products/adpwrswch-a",
            "products/adpullup-a",
            "products/adrpilink-a",
            "products/adsticker-c",
            "products/adusbhook-a",
            "products/adusbstick-a",
          ],
        },
        {
          type: "category",
          label: "Accessories",
          items: [
            "products/axcbl",
            "products/axcnctr",
            "products/axholey",
            "products/axmnt",
          ],
        },
        "catalog/third-party",
      ],
    },

    // ─────────────────────────────── 🔌 HOSTS ────────────────────────────────────
    {
      type: "category",
      label: "🔌 Hosts",
      link: { type: "doc", id: "hw/intro" },
      items: [
        "hw/pc-laptop",
        "hw/raspberry-pi",
        "hw/arduino",
        "hw/microbit",
        "hw/espressif",
        "hw/arcade",
        "hw/phone-tablet",
        "hw/beyond",
        "hw/backup",
      ],
    },

    // ─────────────────────────────── 📚 ADVANCED ─────────────────────────────────
    {
      type: "category",
      label: "📚 Advanced",
      items: [
        {
          type: "category",
          label: "Interfaces",
          link: { type: "doc", id: "interface/intro" },
          items: [
            "interface/usb",
            "interface/i2c",
            "interface/uart",
            "interface/downlink",
            "interface/wireless",
          ],
        },
        {
          type: "category",
          label: "Internal Engine",
          link: { type: "doc", id: "engine/intro" },
          items: [
            "engine/scripting",
            "engine/stdlib",
            "engine/drivers",
            "engine/graphics",
            "engine/filesystem",
            "engine/regions",
            "engine/scheduler",
            "engine/interrupt",
            "engine/pins",
            "engine/stream",
            "engine/coprocessor",
            "engine/daisylink",
          ],
        },
        {
          type: "category",
          label: "Internet of Things",
          link: { type: "doc", id: "iot/intro" },
          items: ["iot/wifi", "iot/cloud"],
        },
        "console",
        "programmer",
        "specs",
        {
          type: "category",
          label: "Languages",
          link: { type: "doc", id: "language/intro" },
          items: [
            "language/python",
            "language/javascript",
            "language/dotnet",
            "language/micropython",
            "language/makecode",
            "language/app-inventor",
            "language/swift",
            "language/excel",
            "language/other",
          ],
        },
      ],
    },

    // ─────────────────────────────── 📥 RESOURCES ────────────────────────────────
    {
      type: "category",
      label: "📥 Resources",
      items: [
        "projects",
        "downloads",
        "release-notes",
        "support",
        "safety",
        "legal",
      ],
    },
  ],
};

export default sidebars;
